import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/Sidebar"; 
import Button from "@/components/Button";
import Link from "next/link";
import clsx from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const buttons = [
    {text: "Inicio", href: "/"},
    {text: "Lista", href: "/caminhao"}, 
    {text: "Adicionar", href: "/caminhao/add"},
    {text: "--Rotas--", href: "/caminhao/rotas", state: "no"},
  ]
  return (
    <div className="h-screen w-screen flex flex-row items-center">
      <SideBar>
        {
        buttons.map((el, ind) => (
            <Link href={el.href} key={ind} 
            className={
              clsx({
                'cursor-not-allowed': el.state === "no",
              })}
            >
                <Button>
                    {el.text}
                </Button>
            </Link>
        ))
        }
      </SideBar>
      <main className="min-h-full w-full">{children}</main>
    </div>
  );
}